window:
  opacity: 0.5
font:
  normal:
    family: Hack Nerd Font
    style:
  size: 13
colors:
  primary:
    background: '0x1e1c31'
    foreground: '#d8d8d8'
    dim_foreground: '0xdbdbdb'
    bright_foreground: '0xd9d9d9'
    dim_background: '0x202020'
    bright_background: '0x3a3a3a'
  cursor:
    text: '0xff271d'
    cursor: '0xfbfcfc'
  normal:
    black: '0x141228'
    red: '0xff5458'
    green: '0x62d196'
    yellow: '0xffb378'
    blue: '0x65b2ff'
    magenta: '0x906cff'
    cyan: '0x63f2f1'
    white: '0xa6b3cc'
  bright:
    black: '0x565575'
    red: '0xff8080'
    green: '0x95ffa4'
    yellow: '0xffe9aa'
    blue: '0x91ddff'
    magenta: '0xc991e1'
    cyan: '0xaaffe4'
    white: '0xcbe3e7'
  dim:
    black: '0x232323'
    red: '0x74423f'
    green: '0x5e6547'
    yellow: '0x8b7653'
    blue: '0x556b79'
    magenta: '0x6e4962'
    cyan: '0x5c8482'
    white: '0x828282'

  cursor:
    style:
      shape: Beam
      blinking: On
      blink_interval: 750
      thickness: 0.25

  shell:
    program: /usr/bin/zsh


  mouse:
    hide_when_typing: true
