#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
setxkbmap es &
#nitrogen --restore &
feh --bg-scale /home/doblux/Imágenes/encrusted-xi-ii.jpg
xsetroot -cursor_name left_ptr
# picom --experimental-backends &
picom &
udiskie &
numlockx &
flameshot &

# ARREGLAR EL PROBLEMA CON LAS APLICACIONES JAVA COMO CLion Inteliji y otras
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
# --------------------------------------------------------------------------

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 	     2
bspc config window_gap           7
bspc config active_border_color \#00ff00
bspc config normal_border_color \#b0b0b0
bspc config focused_border_color \#00ff00

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_follows_pointer true


bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
